Document: trantect-lvm-util
Title: Debian trantect-lvm-util Manual
Author: <insert document author here>
Abstract: This manual describes what trantect-lvm-util is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/trantect-lvm-util/trantect-lvm-util.sgml.gz

Format: postscript
Files: /usr/share/doc/trantect-lvm-util/trantect-lvm-util.ps.gz

Format: text
Files: /usr/share/doc/trantect-lvm-util/trantect-lvm-util.text.gz

Format: HTML
Index: /usr/share/doc/trantect-lvm-util/html/index.html
Files: /usr/share/doc/trantect-lvm-util/html/*.html
