Document: trantect-backup
Title: Debian trantect-backup Manual
Author: <insert document author here>
Abstract: This manual describes what trantect-backup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/trantect-backup/trantect-backup.sgml.gz

Format: postscript
Files: /usr/share/doc/trantect-backup/trantect-backup.ps.gz

Format: text
Files: /usr/share/doc/trantect-backup/trantect-backup.text.gz

Format: HTML
Index: /usr/share/doc/trantect-backup/html/index.html
Files: /usr/share/doc/trantect-backup/html/*.html
